<?php
/**
 * Created by IntelliJ IDEA.
 * User: new
 * Date: 2018-09-03
 * Time: 16:21
 * 读写分离
 */

namespace DB;


use Medoo\Medoo;

class Db extends Medoo
{
    public $container;

    public function __construct($options = null)
    {
        parent::__construct($options);
        if (!empty($options['container'])) {
            $this->container = $options['container'];
        }
    }

    public function select($table, $join, $columns = null, $where = null)
    {
        //pdo切换到从库
        if (!empty($this->container['slave']) && isset($this->container['slave']->pdo)) {
            $this->pdo = $this->container['slave']->pdo;
        }
        return parent::select($table, $join, $columns, $where); // TODO: Change the autogenerated stub
    }

    public function get($table, $join = null, $columns = null, $where = null)
    {
        //pdo切换到从库
        if (!empty($this->container['slave']) && isset($this->container['slave']->pdo)) {
            $this->pdo = $this->container['slave']->pdo;
        }
        return parent::get($table, $join, $columns, $where); // TODO: Change the autogenerated stub
    }

    public function has($table, $join, $where = null)
    {
        //pdo切换到从库
        if (!empty($this->container['slave']) && isset($this->container['slave']->pdo)) {
            $this->pdo = $this->container['slave']->pdo;
        }
        return parent::has($table, $join, $where); // TODO: Change the autogenerated stub
    }

}